# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python27:
      python.version: '2.7'

variables:
  major: 1
  # define minor as a counter with the prefix as variable major, and seed as 100.
  minor: $[counter(variables['major'], 100)]
  a: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 100)]
  form: $[format('Hello {1} {0}', 'John', 'Doe')]

parameters:
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - windows-latest
  - vs2017-win2016
  - ubuntu-latest
  - ubuntu-16.04
  - macOS-latest
  - macOS-10.14
steps:
 - bash: echo $(Build)
#- bash: echo $(minor)
#- bash: echo $(a)
#- bash: echo pipeline.startTime
#- bash: echo $(form)
#- script: echo building $(Build.BuildNumber) with ${{ parameters.image }}
'''
#- download: current
#  artifact: WebApp